### PR TITLE
Prepare for next dev cycle

### PR DESCRIPTION
**Pull request by Thiyanwso2**

### CODE REVIEW

**Comment by AnjanaSenanayake** [comment]
We have to update the Package.md details and their versions mentioned, always when we are doing a release. Package.md api documentation still points to v1.0.0. Need to update it to the latest.

**Review by AnjanaSenanayake — CHANGES_REQUESTED** [review]
We have to update the Package.md details and their versions mentioned, always when we are doing a release. Package.md api documentation still points to v1.0.0. Need to update it to the latest.

**Comment by Thiyanwso2** [comment]
> We have to update the Package.md details and their versions mentioned, always when we are doing a release. Package.md api documentation still points to v1.0.0. Need to update it to the latest.

Is it updated to the latest released version or the snapshot version?

**Comment by Thiyanwso2** [comment]
> We have to update the Package.md details and their versions mentioned, always when we are doing a release. Package.md api documentation still points to v1.0.0. Need to update it to the latest.

Updated

**Review by AnjanaSenanayake — APPROVED** [review]

**Pull request merged**
